flux_version = "1.5.0"
flux_helm_operator_version = "1.2.0"
flux_github_repo_name = "flux-manifests"
flux_git_branch = "main"
flux_git_path = "k8s\\,helm"
github_user = "godacre"
host_name = "MacBook"